ALTER TABLE Orders ADD COLUMN IF NOT EXISTS DeliveryCost DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE Orders ADD COLUMN IF NOT EXISTS Discount DECIMAL(15,2) DEFAULT 0.00;
ALTER TABLE Orders ADD COLUMN IF NOT EXISTS Timber DECIMAL(15,2) DEFAULT 0.00;
