ALTER TABLE appsettings ADD COLUMN IF NOT EXISTS workstarttime VARCHAR(10) DEFAULT '08:00';
ALTER TABLE appsettings ADD COLUMN IF NOT EXISTS workendtime VARCHAR(10) DEFAULT '18:00';
ALTER TABLE appsettings ADD COLUMN IF NOT EXISTS allowedips TEXT DEFAULT '';
